apiVersion: v1
kind: Route
metadata:
  name: deployment-route-app
  labels:
    template: deployment
spec:
  host: app.$(Values.params.spec.APPLICATION_DOMAIN).nip.io
  path: "/" 
  to:
    kind: Service
    name: deployment-svc