apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
  labels:
    app: deployment
    template: deployment
spec:
  selector:
    app: deployment
    template: deployment
  sessionAffinity: None
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8081
status:
  loadBalancer: {}