apiVersion: v1
kind: Route
metadata:
  name: frontend
spec:
  host: www.example.com
  path: "/test" 
  to:
    kind: Service
    name: frontend

# https://docs.openshift.com/container-platform/3.7/dev_guide/routes.html
