apiVersion: v1
kind: Template
metadata:
  name: confmapsecret
  annotations:
    description: 
      "Ejemplo de template para dockerizar y desplegar codigo python, 
      una vez este todo desplegar comenzar el build a mano, usa secrets y config maps"
    iconClass: "icon-play"
    tags: "app"

labels:
  environment: DEV

objects:

# IMAGESTREAMS
# ------------------------
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: confmapsecret-is-app1
    labels:
      app: confmapsecret-app1
      template: confmapsecret
    annotations:
      openshift.io/image.insecureRepository: "true"


# BUILDCONFIG
# ------------------------
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: confmapsecret-bc-app1
    labels:
      app: confmapsecret-app1
      template: confmapsecret
  spec:
    triggers: 
      - type: "ImageChange"
    source:
      type: Git
      contextDir: ${REPO_GIT_CONTEXT_DIR}
      git:
        uri: ${REPO_GIT_URL}
        ref: ${REPO_GIT_BRANCH}
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: ${REPO_GIT_DOCKERFILE_PATH}
        noCache: true
    output:
      to:
        kind: ImageStreamTag
        name: confmapsecret-is-app1:latest


# SERVICES
# ------------------------
- apiVersion: v1
  kind: Service
  metadata:
    name: confmapsecret-svc-app1
    labels:
      app: confmapsecret-app1
      template: confmapsecret
  spec:
    selector:
      app: confmapsecret-app1
      template: confmapsecret
    sessionAffinity: None
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: ${{FLASK_PORT}}
  status:
    loadBalancer: {}


# ROUTERS
# ------------------------
- apiVersion: v1
  kind: Route
  metadata:
    name: confmapsecret-route-app
    labels:
      template: confmapsecret
  spec:
    host: app.${APPLICATION_DOMAIN}.nip.io
    port:
      targetPort: web
    path: "/" 
    to:
      kind: Service
      name: confmapsecret-svc-app1


# CONFIGSMAPS
# ------------------------
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: confmapsecret-cm-apps
    labels:
      typeconfig: apps
      template: confmapsecret
  data: 
    example_property_1: hello
    example_property_2: world
    example.property.file: |-
      property.1=value-1
      property.2=value-2
      property.3=value-3


# SECRETS
# ------------------------
- apiVersion: v1
  kind: Secret
  metadata:
    name: confmapsecret-secret-db
    labels:
      typesecret: db
      template: confmapsecret
  type: Opaque 
  stringData: 
    db_user: system
    db_pass: admin
    

# DEPLOYMENTS
# ------------------------
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: confmapsecret-dc-app1
    labels:
      app: confmapsecret-app1
      template: confmapsecret
  spec:
    replicas: 1
    selector:
      app: confmapsecret-app1
      template: confmapsecret
    template:
      metadata:
        name: confmapsecret-pod-app1
        labels:
          app: confmapsecret-app1
          template: confmapsecret
      spec:
        containers:
          - name: confmapsecret-pod
            image: ${DOCKER_REGISTRY_HOST_PORT}/nalabs/confmapsecret-is-app1
            ports:
              - containerPort: ${{FLASK_PORT}}
                protocol: TCP
            env:
              - name: ENV_VAR 
                value: soy una variable de ambiente
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: confmapsecret-secret-db
                    key: db_user
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: confmapsecret-secret-db
                    key: db_pass
              - name: APP_VAR
                valueFrom:
                  configMapKeyRef:
                    name: confmapsecret-cm-apps
                    key: example_property_1
            envFrom:
              - configMapRef: 
                  name: confmapsecret-cm-apps
              - secretRef: 
                  name: confmapsecret-secret-db


parameters:

- name: APPLICATION_DOMAIN
  description: host de la aplicacion
  value: 192.168.99.101

- name: DOCKER_REGISTRY_HOST_PORT
  description: host y port del registry
  value: 172.30.1.1:5000

- name: REPO_GIT_URL
  description: Url del repo donde esta el codigo fuente
  value: https://github.com/brianwolf/test-openshift.git

- name: REPO_GIT_BRANCH
  description: Branch del repo donde esta el codigo fuente
  value: master

- name: REPO_GIT_CONTEXT_DIR
  description: Path donde esta el codigo fuente dentro del repo
  value: src/python

- name: REPO_GIT_DOCKERFILE_PATH
  description: Path donde esta el Dockerfile dentro del REPO_GIT_CONTEXT_PATH
  value: Dockerfile

- name: FLASK_PORT
  description: Puerto de la aplicacion python
  value: "5000"
